Лабораторна робота №1.Юрченка М.С. Варіант 34(4)

In [ ]:
# Завдання 1: Створити одновимірний масив з непарними числами від 1 до 19 та вивести його значення

import numpy as np
odd_numbers = np.arange(1, 20, 2)
odd_numbers


array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [ ]:
# Завдання 2: Створити двовимірний масив розміром 3x3, заповнити його послідовністю чисел, де кожне наступне число більше попереднього на 2, та вивести його значення

import numpy as np
sequence = np.arange(1, 19, 2)
matrix = sequence.reshape(3, 3)
matrix


array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [ ]:
# Завдання 3: Створити масив розміром 2x2, заповнити його випадковими цілими числами від -5 до 5 та вивести його значення

import numpy as np
random_matrix = np.random.randint(-5, 6, size=(2, 2))
random_matrix


array([[-3,  1],
       [-4,  2]])

In [ ]:
# Завдання 4: Створити масив розміром 6x6, заповнити його випадковими дійсними числами в діапазоні від 0 до 1 та знайти максимальний елемент

import numpy as np
random_matrix = np.random.rand(6, 6)
max_element = np.max(random_matrix)
random_matrix, max_element


(array([[0.23809945, 0.30234562, 0.90044907, 0.10437884, 0.67971345,
         0.79617336],
        [0.74865596, 0.19768683, 0.47311389, 0.93086281, 0.7026322 ,
         0.34711477],
        [0.47662646, 0.44550097, 0.70929715, 0.20427597, 0.35049018,
         0.08266331],
        [0.69693538, 0.84170202, 0.34227277, 0.7268318 , 0.09590745,
         0.27702311],
        [0.12967069, 0.25309648, 0.15837971, 0.47701822, 0.6105805 ,
         0.67073698],
        [0.18428159, 0.71469018, 0.08060988, 0.12443087, 0.07323951,
         0.25536822]]),
 0.9308628107389143)

In [ ]:
# Завдання 5: Створити два одновимірних масиви розміром 4, заповнити їх випадковими цілими числами в діапазоні від -5 до 5 та виконати на них поелементні операції додавання, віднімання та множення

import numpy as np
array1 = np.random.randint(-5, 6, size=4)
array2 = np.random.randint(-5, 6, size=4)
addition_result = array1 + array2
subtraction_result = array1 - array2
multiplication_result = array1 * array2
array1, array2, addition_result, subtraction_result, multiplication_result


(array([-5,  3,  3,  3]),
 array([ 3, -1, -5, -2]),
 array([-2,  2, -2,  1]),
 array([-8,  4,  8,  5]),
 array([-15,  -3, -15,  -6]))

In [ ]:
# Завдання 6: Створити дві матриці 2x2, заповнити їх довільними дійсними числами від 5 до 10 та знайти їх добуток

import numpy as np
matrix1 = 5 + np.random.rand(2, 2) * 5
matrix2 = 5 + np.random.rand(2, 2) * 5
product_matrix = np.dot(matrix1, matrix2)
matrix1, matrix2, product_matrix


(array([[7.41936291, 9.04065422],
        [9.0028359 , 8.58350574]]),
 array([[5.42369403, 8.60164501],
        [8.85666379, 7.34558444]]),
 array([[120.31038918, 130.22761493],
        [124.84985181, 140.49006474]]))

In [ ]:
# Завдання 7: Створити дві матриці розміром 2x3 та 3x3, заповнити їх випадковими цілими числами в діапазоні від 1 до 5 та перемножити їх між собою

import numpy as np
matrix1 = np.random.randint(1, 6, size=(2, 3))
matrix2 = np.random.randint(1, 6, size=(3, 3))
product_matrix = np.dot(matrix1, matrix2)
matrix1, matrix2, product_matrix


(array([[5, 1, 5],
        [1, 4, 2]]),
 array([[5, 1, 5],
        [4, 3, 2],
        [3, 3, 3]]),
 array([[44, 23, 42],
        [27, 19, 19]]))

In [ ]:
# Завдання 8: Створити матрицю розміром 3x3, заповнити її випадковими цілими числами в діапазоні від 1 до 15 та знайти її обернену матрицю

import numpy as np
matrix = np.random.randint(1, 16, size=(3, 3))
if np.linalg.det(matrix) != 0:
    inverse_matrix = np.linalg.inv(matrix)
else:
    inverse_matrix = "Обернена матриця не існує, оскільки визначник дорівнює нулю."
matrix, inverse_matrix


(array([[ 7, 14, 11],
        [12,  3,  8],
        [ 9,  9,  4]]),
 array([[-0.07434944,  0.05328377,  0.09789343],
        [ 0.02973978, -0.08798017,  0.09417596],
        [ 0.10037175,  0.07806691, -0.18215613]]))

In [ ]:
# Завдання 9: Створити матрицю розміром 7x4, заповнити її випадковими дійсними числами в діапазоні від 0 до 1 та транспонувати її

import numpy as np
matrix = np.random.rand(7, 4)
transposed_matrix = matrix.T
matrix, transposed_matrix


(array([[0.82124609, 0.61141756, 0.6232486 , 0.64177666],
        [0.32925425, 0.13393643, 0.19419607, 0.14796019],
        [0.72243725, 0.65111796, 0.36714237, 0.10051912],
        [0.28795095, 0.21110279, 0.93403278, 0.33683504],
        [0.49182587, 0.84505427, 0.86119188, 0.70037069],
        [0.66995527, 0.54784161, 0.68881441, 0.54034997],
        [0.52834023, 0.28222426, 0.14169406, 0.25791515]]),
 array([[0.82124609, 0.32925425, 0.72243725, 0.28795095, 0.49182587,
         0.66995527, 0.52834023],
        [0.61141756, 0.13393643, 0.65111796, 0.21110279, 0.84505427,
         0.54784161, 0.28222426],
        [0.6232486 , 0.19419607, 0.36714237, 0.93403278, 0.86119188,
         0.68881441, 0.14169406],
        [0.64177666, 0.14796019, 0.10051912, 0.33683504, 0.70037069,
         0.54034997, 0.25791515]]))

In [ ]:
# Завдання 10: Створити матрицю розміром 3x4 та вектор розміром 4x1, заповнити матрицю випадковими цілими числами в діапазоні від 1 до 10, а вектор - випадковими дійсними числами від 0 до 1, і знайти добуток матриці на вектор

import numpy as np
matrix = np.random.randint(1, 11, size=(3, 4))
vector = np.random.rand(4, 1)
product_result = np.dot(matrix, vector)
matrix, vector, product_result


(array([[ 4,  3,  7,  5],
        [ 2,  5,  2, 10],
        [10,  3,  6,  3]]),
 array([[0.21062718],
        [0.48853264],
        [0.52107991],
        [0.9034924 ]]),
 array([[10.47312802],
        [12.94100137],
        [ 9.40882638]]))

In [ ]:
# Завдання 11: Створити матрицю розміром 2x3 та вектор розміром 3x1, заповнити матрицю випадковими дійсними числами від 0 до 1, а вектор - випадковими дійсними числами від 0 до 1, і знайти добуток матриці на вектор

import numpy as np
matrix = np.random.rand(2, 3)
vector = np.random.rand(3, 1)
product_result = np.dot(matrix, vector)
matrix, vector, product_result


(array([[0.57568248, 0.13777184, 0.04390743],
        [0.770481  , 0.53296333, 0.24337866]]),
 array([[0.10463798],
        [0.27237496],
        [0.66579425]]),
 array([[0.12699716],
        [0.38782755]]))

In [ ]:
# Завдання 12: Створити дві матриці розміром 5x5, заповнити їх випадковими цілими числами в діапазоні від 1 до 10 та знайти відношення першої матриці до другої (поелементне ділення)

import numpy as np
matrix1 = np.random.randint(1, 11, size=(5, 5))
matrix2 = np.random.randint(1, 11, size=(5, 5))
elementwise_division = matrix1 / (matrix2 + 1e-10)
matrix1, matrix2, elementwise_division


(array([[ 1,  5,  8,  8,  1],
        [10,  1,  8,  2, 10],
        [ 8,  5,  5, 10,  1],
        [ 6,  2,  4,  1,  7],
        [ 8,  1,  7,  6, 10]]),
 array([[ 3, 10, 10,  3,  8],
        [ 5,  1,  2,  2, 10],
        [ 8,  8,  5, 10,  7],
        [ 9,  2,  5,  6,  6],
        [10,  6,  8,  4, 10]]),
 array([[0.33333333, 0.5       , 0.8       , 2.66666667, 0.125     ],
        [2.        , 1.        , 4.        , 1.        , 1.        ],
        [1.        , 0.625     , 1.        , 1.        , 0.14285714],
        [0.66666667, 1.        , 0.8       , 0.16666667, 1.16666667],
        [0.8       , 0.16666667, 0.875     , 1.5       , 1.        ]]))

In [ ]:
# Завдання 13: Створити дві матриці розміром 5x5, заповнити їх випадковими цілими числами в діапазоні від 1 до 10 та знайти суму їх елементів

import numpy as np
matrix1 = np.random.randint(1, 11, size=(5, 5))
matrix2 = np.random.randint(1, 11, size=(5, 5))
sum_matrix1 = np.sum(matrix1)
sum_matrix2 = np.sum(matrix2)
matrix1, matrix2, sum_matrix1, sum_matrix2


(array([[ 5,  2,  4,  4,  7],
        [ 2, 10,  1,  4,  8],
        [ 6,  3,  6,  7,  7],
        [ 4,  7,  5,  3,  9],
        [ 8,  8,  1,  6,  5]]),
 array([[ 8,  6,  2,  2,  9],
        [ 2,  6,  8,  8, 10],
        [ 3,  1,  9,  4,  9],
        [ 8,  9, 10, 10,  8],
        [ 2, 10,  8,  8,  7]]),
 132,
 167)

In [ ]:
# Завдання 14: Створити матрицю розміром 3x3, заповнити її випадковими цілими числами в діапазоні від 1 до 10 та знайти добуток елементів матриці

import numpy as np
matrix = np.random.randint(1, 11, size=(3, 3))
product_elements = np.prod(matrix)
matrix, product_elements


(array([[ 7,  5,  5],
        [ 5,  4, 10],
        [ 6,  7,  6]]),
 8820000)

In [ ]:
# Завдання 15: Створити матрицю розміром 6x6, заповнити її випадковими дійсними числами в діапазоні від -2 до 2 та знайти вектор-стовпчик, що містить середнє арифметичне значення елементів кожного рядка матриці

import numpy as np
matrix = -2 + np.random.rand(6, 6) * 4
mean_vector = np.mean(matrix, axis=1).reshape(-1, 1)
matrix, mean_vector


(array([[ 0.05955917,  1.13259908, -1.25740205, -0.42831307, -0.32073436,
          0.09774092],
        [ 0.89244517,  0.65375186, -1.96370712, -1.13282138,  0.03935869,
          0.90088102],
        [-0.82715405, -0.98270639,  0.56951015,  0.16305686,  0.03147577,
         -0.5210483 ],
        [-1.30127019, -0.88899818,  1.33813976,  1.5356474 , -0.48296678,
         -1.2355077 ],
        [-0.7214629 ,  0.36684095, -0.06555678, -1.50774782, -0.60617947,
         -1.72909092],
        [ 1.48846802, -0.74252602, -1.89757196,  1.63839809,  1.73992929,
         -1.91211405]]),
 array([[-0.11942505],
        [-0.10168196],
        [-0.26114433],
        [-0.17249262],
        [-0.71053282],
        [ 0.05243056]]))

Висновки: виконавши 15 завдань з вступ до машинного навчання.Елементи лінійної алгебри. Навчився створювати матриці.